#!/usr/bin/ruby

require 'pathname'

def backup_file(file_path)
  puts 'Backing up ' + file_path.to_s

  new_path = BACKUP_PATH + file_path.basename

  File.rename(file_path, new_path)
end



BACKUP_PATH = Pathname.new('./backups')

ZSHRC_DESTINATION_PATH = Pathname.new('../.zshrc')
ZSHRC_SOURCE_PATH = Pathname.new('./zsh/.zshrc')

if ZSHRC_DESTINATION_PATH.exist?
  backup_file(ZSHRC_SOURCE_PATH)
end
